# Generated by Django 5.2 on 2025-04-20 05:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_profile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_nome', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_senha', models.CharField(max_length=50)),
                ('user_imagem', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
