# Generated by Django 5.2 on 2025-04-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_perfil_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
    ]
