# Generated by Django 5.2 on 2025-04-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_usuario_rename_livro_ano_livro_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
