# Generated by Django 5.2 on 2025-04-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0008_usuario_email_verificado_usuario_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
