# Generated by Django 5.2 on 2025-04-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_livro_validado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email_verificado',
            new_name='email_confirmado',
        ),
    ]
