# Generated by Django 5.2 on 2025-04-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0010_rename_email_verificado_usuario_email_confirmado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
