# Generated by Django 5.2 on 2025-04-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0011_alter_usuario_email_alter_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
    ]
